version: '3.4'
services:
  db:
    image: mysql:5.7.30
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATA_BASE: rest_api_builders
    ports:
      - "3306:3306"
    networks:
      - builders-network
  rest-api-builders:
    image: pcdias/rest-api-builders
    restart: always
    build: ./CadastroClientes
    working_dir: /CadastroClientes
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - builders-network
networks:
  builders-network:
    driver: bridge